language: r
cache: packages
pandoc_version: 1.19.2.1
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
env:
  global:
  - secure: f/JycbO8keXiYXR2bIiDufgsCLw52Vza0kg88YZZis2FEBhLZZKqWWYRWjPTHZIU+318XAmfOeiO4WtQ/DA4tpweVAJHAUlWHGWmFFhS1/Mz5V0sk7/Eayj3Io3eO4aisPNhB8iPCMiTj8xchHZo3YzdL6FZevnYI+X5TeWRk6XZzd3Wth/9kFwcX8svM0v9tYLUfMjTJCWtj3rLjdzPG0XJzeaz63viDMafc7pBvwxD3AmDaGUxk+d2SGkE++rl/Pl5twEWlBh7S508XGt6xs+cO8o5nFyKaLtqmTnK3UZph6JnA3mYTHexUUtT/p4/jrsk2sVbvRjnR8LkvWPuj1gxJBhkHZTS7M0RBatU0aKTKFeyz6IbRApwvSfFJrdryVqoftomzga1bHzHJ1mEJ+T5E08L50edMuCV7fGuCCDGW+WjfIHMnzxnD00IMiBwUhSL8d7VHb4GoDBgcwphTiexKb4P8RVtNW4QO1Y6Mok6i4bvrlYcyo/bxdTk6dqsvF2r95D0mfRVJi6aAFvYthdyMutjqUL6QIjLbuwxjLrCjoiY9by0CNig1XmNVVsK3aQ0VCJ2qdahSjueLVAmY/W1josv3vu+e6J2fM/eauU2DaqOPFbbP3yibTpxLMszV6MbuEq91Ax4GK0LhcjEeuvrpW49vFXyXzrCdTp6gy8=